version: '3.8'

services:
  api:
    image: poker-api:latest
    container_name: poker-api
    build:
      context: /api
    ports:
      - "3000:3000"
    networks:
      - net
    environment:
      JWT_SECRET: <CUSTOM-JWT-SECRET> # @TODO replace with your secret
      CLIENT_URL: <CUSTOM-CLIENT-URL> # @TODO replace with your custom url (also custom localhost url)
  frontend:
    image: poker-frontend:latest
    container_name: poker-frontend
    build:
      context: /frontend
    ports:
      - "5173:80"
    depends_on:
      - api
    networks:
      - net
    volumes:
      - ./frontend/nginx/local.conf:/etc/nginx/conf.d/default.conf
networks:
  net: