version: '3.8'

services:
  api:
    image: poker-api:latest
    container_name: poker-api
    build:
      context: /api
    ports:
      - "3000:3000"
    networks:
      - net
  frontend:
    image: poker-frontend:latest
    container_name: poker-frontend
    build:
      context: /frontend
    ports:
      - "5173:80"
    depends_on:
      - api
    networks:
      - net
networks:
  net: