version: '3.8'

services:
  api:
    image: poker-api:latest
    container_name: poker-api
    build:
      context: /api
    ports:
      - "3000:3000"
    networks:
      - net
    environment:
      JWT_SECRET: 123456789 # @TODO replace with CI variable reference
      CLIENT_URL: http://poker.frontend.nils-siemsen.local:5173
  frontend:
    image: poker-frontend:latest
    container_name: poker-frontend
    build:
      context: /frontend
    ports:
      - "5173:80"
    depends_on:
      - api
    networks:
      - net
    volumes:
      - ./frontend/nginx/local.conf:/etc/nginx/conf.d/default.conf
networks:
  net: