version: '3.8'

services:
  api:
    image: poker-api:latest
    container_name: poker-api
    build:
      context: ./api
      args:
        - JWT_SECRET=123456789#+´ß
        - ORIGIN=http://poker.localhost
    ports:
      - "3000:3000"
    networks:
      - net
  client:
    image: poker-client:latest
    container_name: poker-client
    build:
      context: ./client
      args:
        - API_URL=http://api.poker.localhost:3000
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - net
    volumes:
      - ./client/nginx/local.conf:/etc/nginx/conf.d/default.conf
      
networks:
  net: