name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{ secrets.TOKEN }}

          - name: '[API] Build Docker Image'
            run: |
              # TODO: build directly via command using build args
              docker build api -t ghcr.io/nils-s-dev/pointing-poker-api:latest --build-arg JWT_SECRET=${{ secrets.SHARED_SECRET }} --build-arg ORIGIN=${{ vars.CLIENT_URL }}
              docker push ghcr.io/nils-s-dev/pointing-poker-api:latest

          - name: '[Client] Build Docker Image'
            run: |
              # TODO: build directly via command using build args
              docker build client -t ghcr.io/nils-s-dev/pointing-poker-client:latest --build-arg API_URL=${{ vars.API_URL }} --build-arg WS_URL=${{ vars.WS_URL }} --build-arg WS_PREFIX=${{ vars.WS_PREFIX }}
              docker push ghcr.io/nils-s-dev/pointing-poker-client:latest
